# Generated by Django 5.2 on 2025-04-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_moneda', models.CharField(max_length=5, unique=True)),
                ('moneda', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
                'ordering': ['moneda'],
            },
        ),
    ]
